@startuml current-system-context
!RELATIVE_INCLUDE = "."
!include c4/C4_Context.puml

title Контекстная диаграмма текущей системы

Person(user, "Пользователь", "Управляет отоплением и просматривает текущую температуру")

System(monolith, "Монолитное приложение", "Приложение на Go с базой данных PostgreSQL")

System_Ext(sensor, "Датчик", "Установлен в доме и предоставляет данные о температуре")

Rel(user, monolith, "Включает и выключает отопление, просматривает температуру", "Веб-интерфейс")
Rel(monolith, sensor, "Передает команды управления и запрашивает температуру", "Синхронное взаимодействие")

@enduml
