@startuml helloworld
!RELATIVE_INCLUDE = "."
!include c4/C4_Context.puml

title C4-PlantUML - проверка локальной библиотеки

Person(user, "Пользователь", "Проверяет подключение C4-PlantUML")
System(system, "Hello World", "Тестовая система")

Rel(user, system, "Использует")

SHOW_LEGEND()
@enduml
